version: "3"
services:
  app:
    container_name: docker-nextjs-api
    build:
      context: docker-nextjs
      dockerfile: Dockerfile
    volumes:
      - ./docker-nextjs:/app
      - ./docker-nextjs/node_modules:/app/node_modules
      - /app/.next
    ports:
      - "3500:3000"
  db:
    image: mysql
    container_name: docker-nextjs-db
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
    # (this is just an example, not intended to be a production configuration)
  prisma:
    container_name: docker-nextjs-prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: localhost
            port: 4466
            user: root
            password: dev
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db